### ISSUE TITLE
list of issues and ideas

### ISSUE THREAD

**Issue by sofianhit** [Goodwy/Dialer#30]
hi 
There is some problems with your "right dialer" app that I love to fix them then I will pay it .
1- When use "add to home screen" (adding a shurtcut icon contact on home screen) 
This icon should connect immediately when pressed , 
but for now it open the dialer options .
so please make it make the call by one click immediately and directly .
2- Please make the search on "Recents" can search all contacts not only "Recents" ,
don’t force me to tab to "contacts" for search a contact that is not in "Recents" .
3- What about record calls ? I need record my calls .
4- Give me option to disable " Bubbles " when press on numbers in "clean" theme .
I love the clean theme but not love the Bubbles that show when click on numbers .
5- In "Recents" , I cant edit a contact directly , so I need a quick edit option , 
so I suggest when click on "avatar" open the contact edit page and when click on
the number make call .
6- Add a sittings icon on the top bar :
there is a lot of space on top so please add icon sittings .
7- I have an issue when using this option "Always display incoming calls on full screen" 
the incoming calls not show on the home screen and lock screen too ,
in home screen I need to slide from top to see a small box then click on it to see full screen call , in lock screen I need to unlock the screen to see a small box then click on it to see full screen call . this make me a crazy .
8- Save the search keywords : 
please add a dropdown menu for recents words that I searched .
This mean : if I searched this word "father" , the next time I click on the search box I will see a dropdown menu with "father" , 
show the last 10 words for example .
9- Please add a mark to your app logo , 
when I make a call my phone ask me which app to use , and your logo is similar to 
my default dialer app .

I hop you fix it 

My phone info:
Redmi note 12
Android version : 14 ukq1.12.917.001
Android secrurity apdate 2023-11-01

how to contact you by email ?

Thanks .

**Comment by sofianhit** [comment]
I thought you were quick to answer.
I deleted your program and no longer need it

**Comment by Goodwy** [comment]
1- You can create a shortcut for a contact and when pressed, the app makes a call.
2- Maybe someday in the future.
3- This feature will not be available until Google starts supporting it.
4- Let's give this feature.
5- Add the ability to go straight to editing.
6- I don't understand which icon you mean.
7- Android blocks the app from accessing the lock screen. Some manufacturers add additional permissions to access the lock screen, we need to give them to our app. Also our app should have permission to display on top of other apps.
8- Maybe someday in the future.
9- Remember your app selection so that Android won't ask you next time.
